project: 
  type: website
  output-dir: docs

website:
  title: "Elle Adams Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/starter-analysis-exercise.qmd
          - text: "READy Exercise"
            file: ready-exercise/ready-exercise.html 
          - text: "Week 4 Data Exercise"
            file: data-exercise/data-exercise.qmd
          - text: "Data Analysis Exercise"
            file: cdcdata-exercise/cdcdata-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/elleadams/ElleAdams-portfolio.git       
format:
  html:
    theme: journal
    highlight: zenburn
    css: styles.css
    toc: FALSE

# This section contributed by Alexandra Tejada-Strop
